const studentData = [
   {
       name: 'Anna Watson',
       id: '#00345',
       level: 300,
       program: 'Real Estate',
       gender: 'Female',
       contact: '00800500342',
       description:'',
       date_of_admission: '2nd May 2024',
       payment_status: 'Have Paid',
       date_of_birth: '3rd February, 2024',
       address: '3rd Avenue OH',
       email: 'klvnafriyie123@gmail.com',
       intake:"",
       official_receipt:"",
       payment_method:"",
       date:"",
       amount_due:"",
       tuition_fee:"",
       miscellaneous:"",
       balance:"",
       remarks:""
   },
    {
        name: 'John Lee',
        id: '#00034',
        level: 100,
        program: 'OFAD',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Andy Tay',
        id: '#00985',
        level: 100,
        program: 'IT Admin',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Bryan Adu',
        id: '#00784',
        level: 100,
        program: 'Real Estates',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Angel Ford',
        id: '#00431',
        level: 200,
        program: 'Paralegal',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Wilmette Arthur',
        id: '#00456',
        level: 400,
        program: 'CSWA',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Gloria John',
        id: '#00674',
        level: 200,
        program: 'Paralegal',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Sandra Sia',
        id: '#00986',
        level: 200,
        program: 'OFAD',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Ben Greenlish',
        id: '#00326',
        level: 100,
        program: 'IT Admin',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Samuel Johnson',
        id: '#00325',
        level: 400,
        program: 'Real Estates',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Gloria John',
        id: '#00674',
        level: 200,
        program: 'Paralegal',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Sandra Sia',
        id: '#00986',
        level: 200,
        program: 'OFAD',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Ben Greenlish',
        id: '#00326',
        level: 100,
        program: 'IT Admin',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Samuel Johnson',
        id: '#00325',
        level: 400,
        program: 'Real Estates',
        gender: 'Male',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Gloria John',
        id: '#00674',
        level: 200,
        program: 'Paralegal',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
    {
        name: 'Sandra Sia',
        id: '#00986',
        level: 200,
        program: 'OFAD',
        gender: 'Female',
        contact: '00800500342',
        description:'',
        date_of_admission: '2 May 2024',
        payment_status: 'Have Paid',
        date_of_birth: '3rd February, 2024',
        address: '3rd Avenue OH',
        email: 'klvnafriyie123@gmail.com',
        intake:"",
        official_receipt:"",
        payment_method:"",
        date:"",
        amount_due:"",
        tuition_fee:"",
        miscellaneous:"",
        balance:"",
        remarks:""
    },
];

export default studentData;
